import os
import io
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH

def format_timestamp(seconds: float) -> str:
    """Formats float seconds into MM:SS string."""
    mins = int(seconds // 60)
    secs = int(seconds % 60)
    return f"{mins:02d}:{secs:02d}"

def export_to_txt(
    title: str, 
    short_summary: str, 
    detailed_summary: str, 
    transcript: str, 
    key_moments: list = None,
    insights: dict = None
) -> str:
    """
    Formats video data into a clean Plain Text (.txt) document.
    """
    lines = []
    lines.append("=" * 60)
    lines.append(f"CLIPMIND AI — VIDEO SUMMARY & TRANSCRIPT REPORT")
    lines.append(f"Title: {title}")
    lines.append("=" * 60)
    lines.append("")
    
    if insights:
        lines.append(f"Tone: {insights.get('tone', 'N/A')} | Sentiment: {insights.get('sentiment', 'N/A')}")
        if insights.get("keywords"):
            lines.append(f"Keywords: {', '.join(['#' + k for k in insights.get('keywords', [])])}")
        lines.append("-" * 60)
        lines.append("")
        
    lines.append("1. EXECUTIVE OVERVIEW")
    lines.append("-" * 30)
    lines.append(short_summary or "No summary available.")
    lines.append("")
    
    lines.append("2. DETAILED THEMATIC BREAKDOWN")
    lines.append("-" * 30)
    lines.append(detailed_summary or "No detailed breakdown available.")
    lines.append("")
    
    if key_moments:
        lines.append("3. KEY MOMENTS & HIGHLIGHTS")
        lines.append("-" * 30)
        for m in key_moments:
            ts = format_timestamp(m.get("start", 0.0))
            hook = m.get("hook", "Highlight")
            lines.append(f"[{ts}] {hook}")
        lines.append("")
        
    lines.append("4. COMPLETE TIME-ALIGNED TRANSCRIPT")
    lines.append("-" * 30)
    lines.append(transcript or "No transcript text available.")
    lines.append("")
    lines.append("=" * 60)
    lines.append("Generated by ClipMind AI — Local Video Intelligence Platform")
    
    return "\n".join(lines)

def export_to_docx(
    title: str, 
    short_summary: str, 
    detailed_summary: str, 
    transcript: str, 
    key_moments: list = None,
    insights: dict = None,
    output_path: str = None
) -> io.BytesIO:
    """
    Creates a styled, professional Word Document (.docx) report.
    Returns io.BytesIO buffer (or writes to file if output_path is provided).
    """
    doc = Document()
    
    # Configure document styles
    PRIMARY_COLOR = RGBColor(30, 41, 59)     # Slate 800
    ACCENT_INDIGO = RGBColor(79, 70, 229)    # Indigo 600
    TEXT_MUTED = RGBColor(100, 116, 139)     # Slate 500
    
    # Document Title Header
    p_title = doc.add_paragraph()
    p_title.paragraph_format.space_after = Pt(2)
    run_title = p_title.add_run("CLIPMIND AI")
    run_title.font.name = "Arial"
    run_title.font.size = Pt(24)
    run_title.font.bold = True
    run_title.font.color.rgb = ACCENT_INDIGO
    
    p_sub = doc.add_paragraph()
    p_sub.paragraph_format.space_after = Pt(14)
    run_sub = p_sub.add_run(f"Video Intelligence Report: {title}")
    run_sub.font.name = "Arial"
    run_sub.font.size = Pt(13)
    run_sub.font.bold = True
    run_sub.font.color.rgb = PRIMARY_COLOR
    
    # Metadata pill box
    if insights:
        p_meta = doc.add_paragraph()
        p_meta.paragraph_format.space_after = Pt(16)
        r_meta = p_meta.add_run(f"Tone: {insights.get('tone', 'Informative')} | Sentiment: {insights.get('sentiment', 'Neutral')}\n")
        r_meta.font.size = Pt(10)
        r_meta.font.italic = True
        r_meta.font.color.rgb = TEXT_MUTED
        if insights.get("keywords"):
            r_kw = p_meta.add_run("Keywords: " + ", ".join(["#" + k for k in insights.get("keywords", [])]))
            r_kw.font.size = Pt(10)
            r_kw.font.color.rgb = ACCENT_INDIGO
            
    # Section 1: Executive Overview
    h1 = doc.add_heading(level=1)
    h1.paragraph_format.space_before = Pt(14)
    h1.paragraph_format.space_after = Pt(6)
    r_h1 = h1.add_run("1. Executive Overview")
    r_h1.font.color.rgb = ACCENT_INDIGO
    
    p_exec = doc.add_paragraph()
    p_exec.paragraph_format.space_after = Pt(12)
    p_exec.add_run(short_summary or "No summary generated.")
    
    # Section 2: Detailed Breakdown
    h2 = doc.add_heading(level=1)
    h2.paragraph_format.space_before = Pt(14)
    h2.paragraph_format.space_after = Pt(6)
    r_h2 = h2.add_run("2. Detailed Thematic Breakdown")
    r_h2.font.color.rgb = ACCENT_INDIGO
    
    for bullet in (detailed_summary or "").split("\n"):
        b_clean = bullet.strip()
        if b_clean:
            p_b = doc.add_paragraph(style='List Bullet')
            p_b.paragraph_format.space_after = Pt(3)
            # Remove leading markdown stars if present
            b_text = b_clean.lstrip("*-• ").strip()
            p_b.add_run(b_text)
            
    # Section 3: Key Moments
    if key_moments:
        h3 = doc.add_heading(level=1)
        h3.paragraph_format.space_before = Pt(14)
        h3.paragraph_format.space_after = Pt(6)
        r_h3 = h3.add_run("3. Key Moments & Timestamps")
        r_h3.font.color.rgb = ACCENT_INDIGO
        
        for m in key_moments:
            p_m = doc.add_paragraph(style='List Bullet')
            p_m.paragraph_format.space_after = Pt(4)
            ts = format_timestamp(m.get("start", 0.0))
            r_ts = p_m.add_run(f"[{ts}] ")
            r_ts.font.bold = True
            r_ts.font.color.rgb = ACCENT_INDIGO
            p_m.add_run(m.get("hook", ""))
            
    # Section 4: Full Transcript
    h4 = doc.add_heading(level=1)
    h4.paragraph_format.space_before = Pt(16)
    h4.paragraph_format.space_after = Pt(6)
    r_h4 = h4.add_run("4. Time-Aligned Transcript")
    r_h4.font.color.rgb = ACCENT_INDIGO
    
    p_tr = doc.add_paragraph()
    p_tr.paragraph_format.space_after = Pt(12)
    p_tr.add_run(transcript or "No transcript available.")
    
    if output_path:
        doc.save(output_path)
        return output_path
        
    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf
